import { FormEvent, useEffect, useState } from 'react';
import { deleteStorageObject, getStorage, listAdminUsers, resetUserPassword, type AdminUser, type StorageObject, type StorageSummary } from '../../api/admin';
import { errorMessage } from '../../api/client';
import { useAuth } from '../../auth/AuthContext';

export function AdminPage() {
  const auth = useAuth(); const [users, setUsers] = useState<AdminUser[]>([]); const [storage, setStorage] = useState<{usage: StorageSummary; items: StorageObject[]} | null>(null); const [query, setQuery] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const refresh = async () => { setError(null); try { const [nextUsers, nextStorage] = await Promise.all([listAdminUsers(query), getStorage()]); setUsers(nextUsers); setStorage(nextStorage); } catch (caught) { setError(errorMessage(caught, '加载管理数据失败')); } };
  useEffect(() => { if (auth.status === 'authenticated' && auth.user.isAdmin) void refresh(); }, [auth.status, auth.user?.isAdmin]);
  async function reset(event: FormEvent<HTMLFormElement>, user: AdminUser) { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get('password') ?? ''); if (password.length < 8) { setError('新密码至少需要 8 位。'); return; } setBusy(user.id); try { await resetUserPassword(user.id, password); event.currentTarget.reset(); } catch (caught) { setError(errorMessage(caught, '重置密码失败')); } finally { setBusy(null); } }
  async function remove(object: StorageObject) { if (!window.confirm(`确认永久删除对象“${object.key}”？这可能使对应文档或头像不可用。`)) return; setBusy(object.key); try { await deleteStorageObject(object.key); await refresh(); } catch (caught) { setError(errorMessage(caught, '删除对象失败')); } finally { setBusy(null); } }
  if (auth.status === 'loading') return <main className="app-shell"><section className="empty-state">加载中</section></main>;
  if (auth.status === 'anonymous') { window.location.replace('/login'); return null; }
  if (!auth.user.isAdmin) return <main className="app-shell"><section className="empty-state">无权限访问</section></main>;
  return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">管理</p><h1>管理控制台</h1></div><div className="user-actions"><a className="secondary-button" href="/admin/audit-logs">审计日志</a><a className="secondary-button" href="/documents">文档</a></div></header>{error ? <p className="form-error">{error}</p> : null}<section className="admin-summary"><article><span>存储对象</span><strong>{storage?.usage.objectCount ?? '-'}</strong></article><article><span>存储占用</span><strong>{storage ? formatSize(storage.usage.totalBytes) : '-'}</strong></article><article><span>用户数</span><strong>{users.length}</strong></article></section><section className="admin-panel"><div className="admin-panel-header"><h2>用户</h2><form onSubmit={(event) => { event.preventDefault(); void refresh(); }}><input aria-label="搜索用户" onChange={(event) => setQuery(event.target.value)} placeholder="邮箱或显示名" value={query}/><button className="secondary-button" type="submit">搜索</button></form></div>{users.map((user) => <article className="admin-user" key={user.id}><div>{user.avatarUrl ? <img alt="" className="admin-avatar" src={user.avatarUrl}/> : null}<span><strong>{user.displayName}</strong><small>{user.email} · {user.authSource === 'local' ? '本地账号' : 'OIDC'}</small></span></div>{user.authSource === 'local' ? <form onSubmit={(event) => void reset(event, user)}><input aria-label={`${user.displayName}的新密码`} minLength={8} name="password" placeholder="新密码" required type="password"/><button className="secondary-button" disabled={busy === user.id} type="submit">重置密码</button></form> : <span className="document-meta">由身份提供方管理</span>}</article>)}</section><section className="admin-panel"><div className="admin-panel-header"><h2>MinIO 对象</h2><button className="secondary-button" onClick={() => void refresh()} type="button">刷新</button></div>{storage?.items.map((object) => <article className="admin-object" key={object.key}><span><strong>{object.key}</strong><small>{formatSize(object.sizeBytes)} · {new Date(object.updatedAt).toLocaleString()}</small></span><button className="secondary-button danger-button" disabled={busy === object.key} onClick={() => void remove(object)} type="button">删除</button></article>)}</section></main>;
}
function formatSize(size: number) { return new Intl.NumberFormat(undefined, { maximumFractionDigits: 1 }).format(size / 1024 / 1024) + ' MB'; }
